export { ReactComponent as DropdownArrow } from "./dropdownArrow.svg";
export { ReactComponent as ArrowBlueRight } from "./arrow-blue-right.svg";
export { ReactComponent as ArrowWhiteRight } from "./arrow-white-right.svg";
export { ReactComponent as BriefCase } from "./briefCase.svg";
// export { ReactComponent as CornerPetal } from "./cornerPetal.svg";
export { ReactComponent as CornerPetalDeep } from "./cornerPetalDeep.svg";
export { ReactComponent as Mark } from "./mark.svg";
export { ReactComponent as ThreeDot } from "./threeDot.svg";
export { ReactComponent as RedTrash } from "./red-trash.svg";
export { ReactComponent as MagGlass } from "./magGlass.svg";
export { ReactComponent as DropDownArrow } from "./dropdownArrow.svg";
export { CornerPetal } from "./CornerPetal";
export { ReactComponent as ViewSvg } from "./view.svg";
export { ReactComponent as EditGreySvg } from "./editGrey.svg";
export { ReactComponent as DeleteRedSvg } from "./deleteRed.svg";
export { ReactComponent as Close } from "./close.svg";
